CREATE TABLE BUILDINGS(
bID INT NOT NULL IDENTITY(1,1),
bName varchar(50),
bStreet varchar(60),
bCity varchar(40),
bState varchar(2),
bZip Int,
bPrimaryAdmin varchar(50)
CONSTRAINT bID_PK PRIMARY KEY(bID));

CREATE TABLE SERVICE_CONTRACT(
sCID int NOT NULL IDENTITY(1,1),
sCProvider varchar(50),
sContractCostPY int,
sCtimeToHonor DATE,
sCRating varchar(10)
CONSTRAINT sCID_PK PRIMARY KEY(sCID));

CREATE TABLE SERVICE_PROVIDERS(
sProviderID INT NOT NULL IDENTITY(1,1),
sProviderName varchar(50),
sProviderDescription varchar(250),
sProviderPrimaryContact varchar(50),
sProviderNumber varchar(15),
sProviderRating varchar(2),
sCID int, --fk
CONSTRAINT sProviderID_PK PRIMARY KEY(sProviderID),
CONSTRAINT sCID_FK FOREIGN KEY(sCID) 
REFERENCES SERVICE_CONTRACT(sCID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
);

CREATE TABLE LARGE_SITE_EQUID_MED
(
LargeEID int NOT NULL IDENTITY(1,1),
LEName varchar(50),
LELoc varchar(10),
LEOwnershipDate DATE,
LECondition varchar(10),
LEAverageUsePerYear int,
LDescription varchar(250),
LCostPerYear money,
LCurrentLoc varchar(10),
sCID int, -- fk
bID int, -- fk
CONSTRAINT LargeEID_PK PRIMARY KEY(LargeEID),
CONSTRAINT bID_FK_LSEM FOREIGN KEY(bID) 
REFERENCES BUILDINGS(bID)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT LServContractID_FK FOREIGN KEY(sCID) 
REFERENCES SERVICE_CONTRACT(sCID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
);

CREATE TABLE MEDIUM_EQUIP_MED
(
mEID int NOT NULL IDENTITY(1,1),
mEName varchar(50),
mELoc varchar(10),
mEOwnershipDate DATE,
mECondition varchar(10),
mEAverageUsePerYear int,
mDescription varchar(250),
mCostPerYear money,
mCurrentLoc varchar(10),
sCID int, -- fk
bID int --fk
CONSTRAINT mEID_PK PRIMARY KEY(mEID),
CONSTRAINT bID_FK_MEM FOREIGN KEY(bID) 
REFERENCES BUILDINGS(bID)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT SERVICE_CONTRACT_FK_MEM FOREIGN KEY(sCID) 
REFERENCES SERVICE_CONTRACT(sCID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
);

CREATE TABLE SMALL_EQUIP_MED
(
sEID int NOT NULL IDENTITY(1,1),
sEName varchar(50),
sELoc varchar(10),
sEOwnershipDate Date,
sEAverageUserPerYear int,
sDescription varchar(250),
sCostPer money,
sCurrentLoc varchar(10),
sCID int, --fk
bID int -- fk
CONSTRAINT sEID_PK PRIMARY KEY(sEID),
CONSTRAINT bID_FK_SEM FOREIGN KEY(bID) 
REFERENCES BUILDINGS(bID)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT SERVICE_CONTRACT_FK_SEM FOREIGN KEY(sCID) 
REFERENCES SERVICE_CONTRACT(sCID)
ON DELETE NO ACTION
ON UPDATE NO ACTION 
);

CREATE TABLE COMPUTERS
(
computerID int NOT NULL IDENTITY(1,1),
[type] varchar(2),
cost money,
softwareID1 int,
softwareID2 int,
softwareID3 int,
softwareID4 int,
softwareID5 int,
cCurrentLoc varchar(10),
cPurchaseDate Date,
sCID int, --fk
bID int -- fk
CONSTRAINT computerID_PK PRIMARY KEY(computerID),
CONSTRAINT bID_FK_C FOREIGN KEY(bID) 
REFERENCES BUILDINGS(bID)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT SERVICE_CONTRACT_FK_c FOREIGN KEY(sCID) 
REFERENCES SERVICE_CONTRACT(sCID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
);


CREATE TABLE OFFICE_EQUIPMENT
(
oEID int NOT NULL IDENTITY(1,1),
oEName varchar(50),
oELoc varchar(10),
oEOwnershipDate Date,
oECondition varchar(10),
oEDescription varchar(250),
oCurrentLoc varchar(10),
bID int -- fk
CONSTRAINT oEID PRIMARY KEY(oEID),
CONSTRAINT bID_FK_OE FOREIGN KEY(bID) 
REFERENCES BUILDINGS(bID)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
);

CREATE TABLE OFFICE_SUPPLIES
(
oSID int NOT NULL IDENTITY(1,1),
oSName varchar(50),
oSBuilding int,
oSHistoricUse int,
oSCost money,
oSCurrentSupplier varchar(50),
oSnumber int,
oSReorderID int, --fk -- not done
bID int -- fk
CONSTRAINT oSID_PK PRIMARY KEY(oSID),
CONSTRAINT bID_FK_OS1 FOREIGN KEY(bID) 
REFERENCES BUILDINGS(bID)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
);

CREATE TABLE BUILDING_OFFICE_INVENTORY
(
inventoryID int NOT NULL IDENTITY(1,1),
bID int, -- fk
sROrderID int --fk with SUPPLY_REODER_LEVELS
CONSTRAINT inventoryID PRIMARY KEY(inventoryID),
CONSTRAINT bID_FK_BOI FOREIGN KEY(bID) 
REFERENCES BUILDINGS(bID)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
);

CREATE TABLE SUPPLY_REORDER_LEVELS
(
sReorderID int NOT NULL IDENTITY(1,1),
sRORDERLEVEL int,
sRestockTime int,
oSID int,
oEID int,
CONSTRAINT sReorderID_PK PRIMARY KEY(sReorderID)
);

CREATE TABLE DISPOSABLE_MEDICIAL_SUPPLIES
(
dMSID int NOT NULL IDENTITY(1,1),
dMSNAME varchar(50),
dMSBuilding int,
dMSHistoricUSE int,
dMSCost money,
dMSCurrentSupplier int,
dMSNumber int,
dMSReorderID int, -- not sure about this
bID int
CONSTRAINT dMSID_PK PRIMARY KEY(dMSID)
CONSTRAINT bID_FK_DMS FOREIGN KEY(bID) 
REFERENCES BUILDINGS(bID)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
);


CREATE TABLE RadioLogical
(
rLID int NOT NULL IDENTITY(1,1),
rLName varchar(50),
rLBuilding int,
rLStateInspection varchar(10),
rLLisence varchar(10),
rLDispoal varchar(50),
rLCostPerUnit money,
rLReorderID int, -- fk not sure about this
bID int -- fk
CONSTRAINT rLID_PK PRIMARY KEY(rLID),
CONSTRAINT bID_FK_R FOREIGN KEY(bID) 
REFERENCES BUILDINGS(bID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
);

CREATE TABLE MedicalWaste
(
mWID int NOT NULL IDENTITY(1,1),
mWType varchar(10),
mWBuilding int,
mWLimit int,
mWCurrent int,
mwRegularRemoval date,
bID int -- fk 
CONSTRAINT mWID_PK PRIMARY KEY(mWID),
CONSTRAINT bID_FK_MW1 FOREIGN KEY(bID) 
REFERENCES BUILDINGS(bID)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
);
